

spring:
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: gch
    password: 123456
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
