eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /service-first/**
      serviceId: service-first
    api-b:
      path: /service-ribbon/**
      serviceId: service-ribbon
    api-c:
      path: /sso-server/**
      serviceId: sso-server
